### ISSUE TITLE
2D position jumps between arms in an impossible way

### ISSUE THREAD

**Issue by edeno** [edeno/Roumis_2018#3]
2D position sometimes jumps from one arm of the maze to another in a manner that would be impossible for the animal to do. Need to:

+ [x] double check the interpolation of the position (@edeno)
+ [x] double check the raw video (@droumis)

Example from Animal JZ1, Day 7, Epoch 2, between 1925 and 1950 seconds:
![screenshot-2018-1-29 2018_01_23_make_sure_linear_distance_works](https://user-images.githubusercontent.com/8053989/35536457-f9d348c8-0514-11e8-956c-9e16d3f64e85.png)

**Comment by edeno** [comment]
Same dataset, but non-interpolated. Issue with 2D position also occurs:

![image](https://user-images.githubusercontent.com/8053989/35584658-aac0a762-05c3-11e8-83a1-5c326b467f89.png)

**Comment by droumis** [comment]
+ [x] offline pos re-track for following epochs and preprocess/upload (@droumis)
('JZ1', 9, 2)
('JZ1', 7, 2)
('JZ1', 4, 2)
('JZ1', 3, 4)
+ [x] convert and upload mp4 vids of raw pos for re-tracking (@droumis)
+ [x] explore new python based pos-tracking (@edeno)

**Comment by edeno** [comment]
I think I figured it out.

My code from the `loren_frank_data_processing` library is using the the non smoothed variables in the `pos` data structure. The smoothed versions of the variables at least doesn't have the jumps between arms. I already went through the trouble of writing new video tracking code, but if I can just use the smoothed variables, that will be fine. I'm in the process of verifying.
